p4_louvre_homepage:
    path:    /
    defaults: { _controller: P4LouvreBundle:Louvre:homepage }

p4_louvre_stepOne:
    path:    /stepOne
    defaults: { _controller: P4LouvreBundle:Louvre:stepOne }

p4_louvre_stepTwo:
    path:    /stepTwo
    defaults: { _controller: P4LouvreBundle:Louvre:stepTwo }

p4_louvre_stepThree:
    path:    /stepThree
    defaults: { _controller: P4LouvreBundle:Louvre:stepThree }
