services:
 #    p4_louvre.Service:
 #      class: P4\LouvreBundle\Service\PriceCalculation

#    p4_louvre.example:
#        class: P4\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
