
services:
     #P4_LouvreBundle.service:
      # class: P4\LouvreBundle\Service\PriceCalculation

#    p4_louvre.example:
#        class: P4\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    #calcul tarif
   # p4_louvre.priceCalculation:
    #    class: P4\LouvreBundle\Service\PriceCalculation
     #   public: true